### ISSUE TITLE
Unary operators

### ISSUE THREAD

**Issue by one-thunder** [one-lightning/java-newbie-exercises#10]
### 3.1 ( Inverse balance on card )
* [x] Define a variable with name `cardBalance` of type `int` and initialize the value with `640`
* [x] Apply `unary minus` operator to variable `cardBalance`
* [x] Print to console
* [x] Apply `unary plus` operator to variable `cardBalance`
* [x] Print to console

Notes:
* Print format `"Available card balance: %cardBalance%."`

### 3.2 ( Baloon height ++ )
* [x] Define a variable with name `baloonHeight` of type `short` and initialize the value with `0`
* [x] Apply `increment` operator to variable `baloonHeight`
* [x] Print to console
* [x] Apply `increment` operator to variable `baloonHeight`
* [x] Print to console
* [x] Repeat steps until `baloonHeight` will be equal to 4
* [x] Print to console

Notes:
* Print format `"Oh! Baloon is %baloonHeight%"(meters) above the ground!!`

### 3.3 ( Money in my pocket -- )
* [x] Define a variable with name `pocketMoney` of type `short` and initialize the value with `30`
* [x] Apply `decrement` operator to variable `pocketMoney`
* [x] Print to console
* [x] Apply `decrement` operator to variable `pocketMoney`
* [x] Print to console
* [x] Repeat steps until `pocketMoney` will be equal to 26
* [x] Print to console

Notes:
* Print format `"Here, take one dollar. I still got %pocketMoney%$ left bro!`

### 3.4 ( A small sweet lie )
* [x] Define a variable with name `isJonAtTheOffice` of type `boolean` and initialize the value with `false`
* [x] Apply `Logical complement operator` operator to variable `isJonAtTheOffice`
* [x] Print to console

Notes:
* Print format `"It's %isJonAtTheOffice%, I think I saw him today.`

### 4.1 ( Height quiz ( in centimeters ) )
* [x] Define a variable with name `jonHeight` of type `int` and initialize the value with `11`
* [x] Define a variable with name `billHeight` of type `int` and initialize the value with `12`
* [x] Define a variable with name `lennyHeight` of type `int` and initialize the value with `9`
* [x] Print to console `Welcome to height quiz! \n`
* [x] Print to console `Jon ( %jonHeight cm % ) is shorter then Bill ( %billHeight% cm ) ? Answer : %???% ` *hint ( `less then` operator )*
* [x] Print to console `Bill ( %billHeight cm % ) is equal to Lenny ( %lennyHeight% cm ) ? Answer : %???% ` *hint ( `equal to` operator )*
* [x] Print to console `Lenny ( %lennyHeight cm % ) is shorter then Jon ( %jonHeight% cm ) ? Answer : %???% ` *hint ( `less then` operator )*

### 4.2 ( Facebook likes quiz )
* [x] Define a variable with name `jonPhotoLikes` of type `int` and initialize the value with `23`
* [x] Define a variable with name `billPhotoLikes` of type `int` and initialize the value with `97`
* [x] Define a variable with name `lennyPhotoLikes` of type `int` and initialize the value with `8`
* [x] Print to console `Welcome to Facebook likes quiz! \n`
* [x] Print to console `Jon's ( %jonPhotoLikes% ) are higher then Bill's ( %billPhotoLikes% ) ? Answer : %???% ` *hint ( `greater than` operator )*
* [x] Print to console `Bill's ( %billPhotoLikes% ) are less then Lenny's ( %lennyPhotoLikes% ) ? Answer : %???% ` *hint ( `less than` operator )*
* [x] Print to console `Lenny's ( %lennyPhotoLikes% ) are equal to then Jon's ( %jonPhotoLikes% ) ? Answer : %???% ` *hint ( `equal to` operator )*

**Comment by one-lightning** [comment]
Approved by @one-thunder :)
