### ISSUE TITLE
Sequential flow control

### ISSUE THREAD

**Issue by one-thunder** [one-lightning/java-newbie-exercises#24]
### 1.1 (SimpleBlocks)
* [x] Create a `sequential` flow control block using :
```
{
   // Some code goes here.
}
```
* [x] Inside this block output to console the following:
```
* * * * *
 * * * * *
* * * * *
 * * * * *
* * * * *
```

* [x] Create another `sequential` flow control block and inside this block output to console:
```
* * * * *
*       *
*       *
*       *
* * * * *
```
* [x] Create another `sequential` flow control block and inside this block output to console:
```

*     *    
 *   *        
  * *        
   *    
```

**Comment by one-lightning** [comment]
Done!
