### ISSUE TITLE
Conditional Flow Control

### ISSUE THREAD

**Issue by one-thunder** [one-lightning/java-newbie-exercises#25]
### 2.1 (DatingMatchParams)
* [x] Define a variable of type `bool` with the name `isMale` and assign it a value of `false`
* [x] Define a variable of type `bool` with the name `isEyeColorMatched` and assign it a value of `true`
* [x] Define a variable of type `bool` with the name `isHairColorMatched` and assign it a value of `true`
* [x] Define a variable of type `bool` with the name `isHeightMatched` and assign it a value of `false`
* [x] Define a variable of type `bool` with the name `isBodyTypeMatched` and assign it a value of `true`
* [x] Create a conditional `if` block with the following expression `(isEyeColorMatched && isHairColorMatched) OR (isHeightMatched && isBodyTypeMatched)`
* [x] Inside the created `if` block output to console the following:
* [x] Apply `ternary` operator with the following expression `isMale ? "him" : "her"`
```
Yay finally found %him/her%!
```

### 2.2 (WorkMeeting)
* [x] Define a variable of type `short` with the name `currentDay` and assign it a value of `25`
* [x] Define a variable of type `short` with the name `scheduledDay` and assign it a value of `25`
* [x] Create a conditional `if` block with the following expression `(currentDay == scheduledDay )`
* [x] Inside created `if` block output the following to console:
```
Ok gotta go to the meeting!
```
* [x] Create a conditional `if` block with the following expression `(currentDay != scheduledDay )`
* [x] Inside created `if` block output the following to console:
```
Not today babe! 
```

### 2.3 (CalendarMeeting)
* [x] Define a variable of type `short` with the name `currentDay` and assign it a value of `25`
* [x] Define a variable of type `short` with the name `currentMonth` and assign it a value of `8`
* [x] Define a variable of type `short` with the name `currentYear` and assign it a value of `2019`
* [x] Define a variable of type `short` with the name `scheduledDay` and assign it a value of `21`
* [x] Define a variable of type `short` with the name `scheduledMonth` and assign it a value of `8`
* [x] Define a variable of type `short` with the name `scheduledYear` and assign it a value of `2019`
* [x] Define a variable of type `boolean` with the name `isDayPassed` and assign it a value of :
```
(currentDay > scheduledDay)
```
* [x] Define a variable of type `boolean` with the name `isMonthPassed` and assign it a value of :
```
(currentMonth > scheduledMonth)
```
* [x] Define a variable of type `boolean` with the name `isYearPassed` and assign it a value of :
```
(currentYear > scheduledYear)
```
* [x] Define a variable of type `boolean` with the name `isScheduledMeetingPassed` and assign to it the following expression:
```
isDayPassed && isMonthPassed && isYearPassed
```
* [x] Define a conditional `if` block with the following expression `(isScheduledMeetingPassed)`
* [x] Inside created `if` block output the following:
```
The meeting has already passed. You missed it.
```
* [x] Break the program from executing using `return` break at the end of the `if` block
* [x] Outside of the `if` block output to console
```
You have an upcoming meeting soon.
```

### 2.4 (PartyInvitiation)
* [x] Define a variable of type `boolean` with name `isAccepted`
* [x] Assign to `isAccepted` the value of `true`
* [x] Create a conditional `if ... else` block with expression `(isAccepted)`.
* [x] In the `true block` output the following to console:
```
Ok let's go to the party!
```
* [x] In the `false block` output the following to console:
```
Not today babe, not today!
```

### 2.5 (UniversityComitee)
* [x] Define a variable of type float with name `minGradesForBudget` and assign it a value of `9.2`
* [x] Define a variable of type float with name `minGradesForContract` and assign it a value of `7.0`
* [x] Define a variable of type `boolean` with name `isDirectorsSon` and assign it a value of `false`
* [x] Define a variable of type `float` with name `gradesAtMath` and assign it a value of `7.5`
* [x] Define a variable of type `float` with name `gradesAtLiterature` and assign it a value of `6.2`
* [x] Define a variable of type `float` with name `gradesAtPhysics` and assign it a value of `9.1`
* [x] Define a variable of type `float` with name `gradesAtComputerScience` and assign it a value of `10.0`
* [x] Begin with create a `nested if block`.
* [x] First block should contain the expression `isDirectorsSon == true`
* [x] Inside the first block output to console 
```
Congrats, Jonny you've entered our university! You are lucky to have your father being a director of this university...with this marks of yours....anyway! Have a nice day!
```
* [x] Second block should have the expression of 
```
gradesAtMath > minGradesForBudget AND
gradesAtLiterature > minGradesForBudget AND
gradesAtPhysics > minGradesForBudget AND
gradesAtComputerScience > minGradesForBudget
 ```
* [x] Inside the second block output to console 
```
Congrats you have joined our university on Budget basis, please study well!
```
* [x] Third block should have the expression of 
```
gradesAtMath > minGradesForContract AND
gradesAtLiterature > minGradesForContract AND
gradesAtPhysics > minGradesForContract AND
gradesAtComputerScience > minGradesForContract
 ```
* [x] Inside the third block output to console 
```
Congrats you have joined our university on Contract basis, please study well!
```
* [x] At last create an `else` block
* [x] Output to console:
```
Sorry to say you that but your grades are not high enough for our university. Bye!
```

### 2.6 (TreeHeight)
* [x] Define a variable of type `int` with name `treeHeightInMeters` and assign it a value of `16`
* [x] Create a `nested if` block.
* [x] First `if` block the expression should be: `treeHeightInMeters >= 40`, in this block output to console:
```
COLOSSAL TREE!
```
* [x] Next `else ... if` block the expression should be: `treeHeightInMeters >= 30`, in this block output to console:
```
GIGANTIC TREE!
```
* [x] Next `else ... if` block the expression should be: `treeHeightInMeters >= 20`, in this block output to console:
```
WHAT A TALL TREE!
```
* [x] Next `else ... if` block the expression should be: `treeHeightInMeters >= 10`, in this block output to console:
```
Wow this is very old tree!
```
* [x] Next `else ... if` block the expression should be: `treeHeightInMeters >= 5`, in this block output to console:
```
Beautifull grownup tree!
```
* [x] Next `else ... if` block the expression should be: `treeHeightInMeters >= 1`, in this block output to console:
```
Small little sapling))
```

Now play with this program with different **input values** 💟 :)

### SWITCH-CASE-DEFAULT

![image](https://user-images.githubusercontent.com/32410574/58747582-d91b5d00-8475-11e9-914c-c333a86df9fb.png)

### 2.7 (DogCommands)
* [x] Define a variable of type `short` with name `dogCommandID` and assign it a value of `0`
* [x] Create a `switch` branch with the following expression inside `dogCommandID`
* [x] Create a `case` branch with the value of `0`
* [x] Output to console `*sitting still*`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `1`
* [x] Output to console  `🐕*sitting still*`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `2`
* [x] Output to console  `🐶 BARK BARK!!`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `3`
* [x] Output to console  `💢RRRRRrrRRRRRRrrrrrARGHRGRGRGGRR`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `777`
* [x] Create a `case` branch with the value of `888`
* [x] Create a `case` branch with the value of `999`
* [x] Output to console `🍖 OMNOMNOMNOM 🍖`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `111`
* [x] Create a `case` branch with the value of `222`
* [x] Create a `case` branch with the value of `333`
* [x] Output to console `⚽️🎈🏈`
* [x] Add a `break`

Notes:
* Add comments for each case and describe what each command is suppose to do.
* To show the icons in java console just copy the characters from here, and change the file encoding if required.

### 2.8 (Animals)

**New variable type**
[Java enums](https://www.w3schools.com/java/java_enums.asp)
(We will learn more about them later.)

**Interesting documentation**
[Taxonomy (biology)](https://en.wikipedia.org/wiki/Taxonomy_(biology))

* [x] Create an enum at **class level** with name `EAnimals` and the following values:
```
Dog,
Cat,
Bird,
Rabbit,
Dragon,
Pig,
Peataceok // Russian word that means Pig's nose :)
Horse,
Rhino,
Lion
```
* [x] Define a variable of type `EAnimals` with name `selectedAnimal` and assign it a value of `EAnimals.Peataceok `
* [x] Create a `switch` branch with the following expression inside `selectedAnimal`
* [x] Create a `case` branch with the value of `EAnimals.Dog`
* [x] Output to console `🐩 Bark bark!`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `EAnimals.Cat`
* [x] Output to console ` 🐱 Meeaw!`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `EAnimals.Bird`
* [x] Output to console ` 🐦 Kuaarrr!`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `EAnimals.Rabbit`
* [x] Output to console ` 🐰 Knuff knuff!`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `EAnimals.Dragon`
* [x] Output to console `🐉 RooooOOOOAAAR! ~🔥~🔥~🔥  `  
* [x] Add a `break`
* [x] Create a `case` branch with the value of `EAnimals.Pig`
* [x] Create a `case` branch with the value of `EAnimals.Pitaciok`
* [x] Output to console `🐷🐽 Oink oink!`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `EAnimals.Horse`
* [x] Output to console `🐴 Niiuaaahahaha `
* [x] Add a `break`
* [x] Create a `case` branch with the value of `EAnimals.Rhino`
* [x] Output to console `🦏 Brrrrr`
* [x] Add a `break`
* [x] Create a `case` branch with the value of `EAnimals.Lion`
* [x] Output to console `🦁 Roooarc!`
* [x] Add a `break`
* [x] Add a default case and output to console `👾 No such animal found! `  

Notes:
* To show the icons in java console just copy the characters from here, and change the file encoding if required.

### 2.9 (Theatre)

* [x] Define a variable of type `boolean` with name `hasJonEnjoyedTheMovie` and assign it a value of `true`
* [x] Define a variable of type `boolean` with name `hasIrenEnjoyedTheMovie` and assign it a value of `false`
* [x] Define a variable of type `boolean` with name `hasBridgetEnjoyedTheMovie` and assign it a value of `true`
* [x] Output to console
```
Mark: So guys, what do you think about this movie? But if you didn't enjoy it, thats bad, dont be silent about it : )\n
```
* [x] Create a `sequential if` with the expression of `hasJonEnjoyedTheMovie`
* [x] Inside this block output to console:
```
Jon: Wow the movie was great!!\n
```
* [x] Create a `sequential if` with the expression of `hasIrenEnjoyedTheMovie`
* [x] Inside this block output to console:
```
Iren: Yeah I kinda liked it too!\n
```
* [x] Create a `sequential if` with the expression of `hasBridgetEnjoyedTheMovie`
* [x] Inside this block output to console:
```
Bridget: OH. MY. GOOOD!
```

### 2.10 (TryHard)

* [x] Create an `enum` on the class level with the name `ETaskStatus` with the following enumeration:
```
NotReady,
ReadyToPlay
InProgress,
ReadyForTesting,
TestingInProgress,
Done,
Reopened
```
* [x] Define a variable of type `ETaskStatus` with the name `myTask` and assign it a value of `ETaskStatus.InTesting`
* [x] Define a variable of type `String` with name `labelPM` and assign it a value of ` [ 🙎 Project Manager ]`
* [x] Define a variable of type `String` with name `labelDev` and assign it a value of ` [ 👨‍💻 Developer ]`
* [x] Define a variable of type `String` with name `labelTester` and assign it a value of ` [ 🕵️‍♀️ Tester ]`
* [x] Start by creating first block for a `conditional if`.
* [x] First block with expression `myTask == ETaskStatus.NotReady`
* [x] Output to console 
```
Me: Hmm I cant start doing it, this should be reviewed by %labelPM%
```
* [x] Next block  with expression `myTask == ETaskStatus.ReadyToPlay`
* [x] Output to console
```
Me: This is not my job I think, It should be implemented by a %labelDev%
```
* [x] Next block  with expression `myTask == ETaskStatus.InProgress`
* [x] Output to console
```
Me: Oh thats so cool, finally this task is being work on by a %labelDev%. Good job Timmy!` 
```
* [x] Next block  with expression `myTask == ETaskStatus.ReadyForTesting`
* [x] Output to console 
```
Me: Oh look what we've got here hehe. This might be a task for a 
I can start working on this...Its time for 🎧 music, but, only after a cup of ☕️ cofee, of course :) `     
```
* [x] Next block  with expression `myTask == ETaskStatus.TestingInProgress`
* [x] Output to console 
```
Me: Seems like all criteria are met, It's fine I think. I just love to be a  %labelTester%
Ok, time to play some 🏓 and close the task after that. Yay!`      
```
* [x] Next block  with expression `myTask == ETaskStatus.Done`
* [x] Output to console 
```
%labelTester% : Congratulations! You did it!:)
%labelDev%: Hell yeaaaah! Finally some 🍺 now!`        
```
* [x] Next block  with expression `myTask == ETaskStatus.Reopened`
* [x] Output to console 
```
%labelTester% : Emmm, sorry to say that Timmy but I think now you broke something :) 😇  
%labelDev% : OH SH** 💢

**Comment by one-lightning** [comment]
Done!
