### ISSUE TITLE
Assignment operator

### ISSUE THREAD

**Issue by one-thunder** [one-lightning/java-newbie-exercises#8]
### 1 ( TV Channels )
* [x] Define an unitialized variable with name `channelName`
* [x] Assign it a value of `Prime TV`
* [x] Print `channelName` to console
* [x] Re-assign the value to `Europa TV`
* [x] Print `channelName` to console
* [x] Re-assign the value to `Muz TV`
* [x] Print `channelName` to console
* [x] Re-assign the value to `"none"`
* [x] Print `channelName` to console

**Comment by one-lightning** [comment]
Done

**Comment by one-thunder** [comment]
Approved:D
